export const FETCH_EVENTS = "FETCH_EVENTS";

export const GET_ALL_EVENT_CATEGORIES = "GET_ALL_EVENT_CATEGORIES";
export const SHOW_ALL_EVENTS = "SHOW_ALL_EVENTS";

export const SELECT_CATEGORY = "SELECT_CATEGORY";
export const SELECT_EVENT = "SELECT_EVENT";

export const SET_MY_LOCATION = "SET_MY_LOCATION";

export const OPEN_INFO_BOX = "OPEN_INFO_BOX";
export const CLOSE_INFO_BOX = "CLOSE_INFO_BOX";
