export const FETCH_EVENTS = "FETCH_EVENTS";
export const GET_ALL_EVENT_CATEGORIES = "GET_ALL_EVENT_CATEGORIES";
export const SHOW_ALL_EVENTS = "SHOW_ALL_EVENTS";
export const SELECT_CATEGORY = "SELECT_CATEGORY";
export const SELECT_EVENT = "SELECT_EVENT";
export const UNSELECT_EVENT = "UNSELECT_EVENT";
